config/routes.rb
Gymsavvy::Application.routes.draw do

  get "exercises/index"

  root to: 'users#new'

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"

  get "bulking_up" => "admin_programs#bulking", :as => "bulking"
  get "lean_machine" => "admin_programs#lean", :as => "lean"
  get "lose_a_few" => "admin_programs#lose", :as => "lose"

  get "pear_shape" => "admin_programs#pear", :as => "pear"
  get "apple_shape" => "admin_programs#apple", :as => "apple"
  get "hour_glass_shape" => "admin_programs#hour", :as => "hour"
  get "celery_shape" => "admin_programs#celery", :as => "celery"

  get "edit/:id" => "program_sets#clone_program", :as => "clone_program"

  get "common_injuries" => "admin_programs#injuries", :as => "injuries"
  get "avoid_injury" => "admin_programs#avoid", :as => "avoid"

  resources :sessions
  resources :users
  resources :program_sets
  resources :exercises

end

app/views/shared/_sign_up_log_in.html.erb
  <div id="formsleftside">
    <div class="signupformouter">
      <div class="signupforminner">
        <h1>Sign Up!</h1>

        <%= form_for @user do |f| %>
          <% if @user.errors.any? %>
            <div class="error_messages">
              <h2>Form is invalid</h2>
              <ul>
                <% @user.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

          <p>
            <%= f.label :email %><br />
            <%= f.text_field :email %>
          </p>
          <p>
            <%= f.label :password %><br />
            <%= f.password_field :password %>
          </p>
          <p>
            <%= f.label :password_confirmation %><br />
            <%= f.password_field :password_confirmation %>
          </p>
            Male <%= f.radio_button :mf, true %> 
            Female <%= f.radio_button :mf, false %>
          <p class="Sign Up"><%= f.submit %></p>
          
        <% end %>
      </div>
    </div>
  </div>

  <div class="or">
    <h2>OR</h2>
  </div>


  <div id="formsrightside">
        <div class="loginwhichcnt">
      <div class="whichform">
        <div class="imagecntfor">
          <div class="loginbelow">
            <p>If your already a member<br /> use the login below</p>
          </div>
        </div>
        <div class="imagecntfor">
          <div class="signupright">
            <p>If your not yet a member<br /> just use the sign up on your right</p>
          </div>
        </div>
      </div>
      <div class="loginformouter">
        <div class="loginforminner">
          <h1>Log in!</h1>

          <%= form_tag sessions_path do %>
            <p>
              <%= label_tag :email %><br />
              <%= text_field_tag :email, params[:email] %>
            </p>
            <p>
              <%= label_tag :password %><br />
              <%= password_field_tag :password %>
            </p>
            <p class="button"><%= submit_tag "Log in" %></p>
          <% end %>
        </div>
      </div>
    </div>    
  </div>