config/routes.rb
Gymsavvy::Application.routes.draw do

  get "exercises/index"

  root to: 'users#new'

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"

  get "bulking_up" => "admin_programs#bulking", :as => "bulking"
  get "lean_machine" => "admin_programs#lean", :as => "lean"
  get "lose_a_few" => "admin_programs#lose", :as => "lose"

  get "pear_shape" => "admin_programs#pear", :as => "pear"
  get "apple_shape" => "admin_programs#apple", :as => "apple"
  get "hour_glass_shape" => "admin_programs#hour", :as => "hour"
  get "celery_shape" => "admin_programs#celery", :as => "celery"

  get "edit/:id" => "program_sets#clone_program", :as => "clone_program"

  get "common_injuries" => "admin_programs#injuries", :as => "injuries"
  get "avoid_injury" => "admin_programs#avoid", :as => "avoid"

  resources :sessions
  resources :users
  resources :program_sets
  resources :exercises

end

app/controllers/admin_programs_controller.rb
class AdminProgramsController < ApplicationController

	before_filter :set_user

	# Guys preset programmes section

	def bulking
		@bulking_programmes = @admin_user.program_sets.where(category: "bulking")
	end

	def lean
		@lean_programmes = @admin_user.program_sets.where(category: "lean")
	end

	def lose
		@lose_weight_programmes = @admin_user.program_sets.where(category: "lose")
	end

	# Girls preset programmes section

	def pear
		@pear_shape_programmes = @admin_user.program_sets.where(category: "pear")
	end
					
	def apple
		@apple_shape_programmes = @admin_user.program_sets.where(category: "apple")
	end

	def hour
		@hour_glass_programmes = @admin_user.program_sets.where(category: "hour")
	end
	
	def celery
		@tube_programmes = @admin_user.program_sets.where(category: "celery")
	end

	# Injuryed section

	def injuries
	end

	def avoid
	end


	def set_user
		@user = User.new
		@admin_user = User.find_by_email("support@gymsays.co.uk")
	end

end

app/helpers/admin_programs_helper.rb
module AdminProgramsHelper
end

app/views/admin_programs/_shape_programmes.html.erb
<div class="setprogspeech">
	<p> 
		"Here are a couple of workout routines to get you started. Sign up or Sign in if you already have an account and alter the programmes to suit you. There's a huge range of exercises to choose from and more being added every day!"
	</p>
</div>

<div class="setprog">
	<% shape_programmes.each do |program_set| %>

	<div class="setprogname">
		<h1><%= program_set.name %></h1>
	</div>
	<div class="setprogdesc">
		<p><%= program_set.description %></p>
	</div>

		<div class="progclonewrap">
			<div class="<%= blue_pink(program_set, 'setprogbox') %>">

				<% program_set.programs.each do |program| %>

					 
			            <div class="<%= blue_pink(program_set, 'setexercise') %>">

			                <div class="setinfo <%=  font_color(program.exercise) %>" >
			                  <h2><%= program.exercise.name %></h2>
			                  <div class="setdetailcnt">			                                      
			                    <% if !program.reps.blank? %>
			                      <div class="setprogdetails">
			                        <h1>Reps</h1>
			                        <span><%= program.reps %></span>
			                      </div>
			                    <% end %>
			                    <% if !program.sets.blank? %>
			                      <div class="setprogdetails">
			                        <h1>Sets</h1>
			                        <span><%= program.sets %></span>
			                      </div>
			                    <% end %>
			                    <% if !program.weight.blank? %>
			                      <div class="setprogdetails">
			                        <h1>Weight</h1>
			                        <span><%= "#{program.weight} #{program.weight_unit}" %></span>
			                      </div>
			                    <% end %>		                    
			                    <% if !program.distance_unit.blank? && !program.distance.blank? %>
			                      <div class="setprogdetails">
			                        <h1>Distance</h1>
			                        <span><%= "#{program.distance} #{program.distance_unit}" %></span>
			                      </div>
			                    <% end %>
			                    <% if !program.swim_distance_unit.blank? && !program.distance.blank?  %>
			                      <div class="setprogdetails">
			                        <h1>Distance</h1>
			                        <span><%= "#{program.distance} #{program.swim_distance_unit}" %></span>
			                      </div>
			                    <% end %>
			                    <% if !program.minutes.blank? %>
			                      <div class="setprogdetails">
			                        <h1>Minutes</h1>
			                        <span><%= program.minutes %></span>
			                      </div>
			                    <% end %>
			                    <% if !program.hours.blank? %>
			                      <div class="setprogdetails">
			                        <h1>Hours</h1>
			                        <span><%= program.hours %></span>
			                      </div>
			                    <% end %>
			                  </div>
			                    

			                </div>   
			            </div>
					
				<% end %>
			</div>

			<div class="<%= blue_pink(program_set, 'clonebox') %>">
				<p>Click below to copy this programme. Personalise it to suit you and have a great workout!</p>
				<div class="clonebtncnt"><%= link_to "CLONE \nProgramme", clone_program_path(program_set), class: "clonebtn" %></div>
			</div>

		</div>
	<% end %>
</div>

app/views/admin_programs/apple.html.erb
<div class="signlog">
  <%= render "shared/sign_up_log_in" %>
</div>

<div class="temptitle">
	<h1>Apple shape</h1>
</div>

<div class="bodyinfowrap">
	<div class="bodyshapeimage">
		<p>image to come</p>
	</div>
	<div class="bodyshapeinfocnt">
		<p><%=
			"The apple shape - You have broader shoulders and bust, and narrower hips. You carry most of your weight around your midriff and bust. There could be health concerns if your waist measures more than 35 inches. Now for the good news; you will be able to lose weight and reshape yourself with a good programme of exercise routines and a healthy diet. Kate Winslett and Catherine Zeta-Jones are both examples of apple shapes."
		%></p>
	</div>

</div>
<hr>

<%= render partial: "shape_programmes", :locals => { shape_programmes: @apple_shape_programmes } %>

app/views/admin_programs/avoid.html.erb
<div class="signlog">
  <%= render "shared/sign_up_log_in" %>
</div>

<div class="temptitle">
	<h1>Avoid injury</h1>
</div>

<div class="contocome">
	<p>Content to be added shortly</p>
</div>

app/views/admin_programs/bulking.html.erb
<div class="signlog">
  <%= render "shared/sign_up_log_in" %>
</div>

<div class="temptitle">
  <h1>Bulking up</h1>
</div>

<div class="bodyinfowrap">
	<div class="bodyshapeimage">
		<p>image to come</p>
	</div>
	<div class="bodyshapeinfocnt">
		<p><%=
			"Pellentesque convallis varius turpis ut tincidunt. Curabitur fermentum, ante a viverra adipiscing, dolor eros consequat est, eu ultricies risus lectus sollicitudin risus. Etiam eget rutrum purus. Etiam eu ullamcorper ligula. Fusce mi urna, auctor non enim id, varius elementum odio. Cras ut diam orci. Aenean a nibh rutrum, eleifend ligula non, sagittis augue. Quisque id aliquet nisi, ac pulvinar neque."
		%></p>
	</div>

</div>
<hr>

<%= render partial: "shape_programmes", :locals => { shape_programmes: @bulking_programmes } %>

app/views/admin_programs/celery.html.erb
<div class="signlog">
  <%= render "shared/sign_up_log_in" %>
</div>

<div class="temptitle">
	<h1>Celery shape</h1>
</div>

<div class="bodyinfowrap">
	<div class="bodyshapeimage">
		<p>image to come</p>
	</div>
	<div class="bodyshapeinfocnt">
		<p><%=

			"The celery shape - You have a straight and long body with slim hips. Your bust and hips are pretty much the same size. You can be perceived as boyish, due to your lack of curves and your chest tends to be relatively flat. The waist is just slightly smaller. You don’t gain much weight or muscle mass easily. The good news is that you tend to lose weight evenly. Kate Moss and Kiera Knightly are both famous tube shaped ladies."
		%></p>
	</div>

</div>
<hr>

<%= render partial: "shape_programmes", :locals => { shape_programmes: @tube_programmes } %>

app/views/admin_programs/hour.html.erb
<div class="signlog">
  <%= render "shared/sign_up_log_in" %>
</div>

<div class="temptitle">
	<h1>Hour glass shape</h1>
</div>

<div class="bodyinfowrap">
	<div class="bodyshapeimage">
		<p>image to come</p>
	</div>
	<div class="bodyshapeinfocnt">
		<p><%=
		
			"The hourglass shape - Hips and bust are almost of equal size, with a narrow waist, but you are in proportion. Hourglass figures tend to be reasonably well balanced, and can adapt to most types of training. Cross training, cycling, running and rowing are all great forms of cardiovascular or aerobic exercise for the hourglass.You will tend to lose and gain weight evenly over your body. Marilyn Monroe and Kelly Brook are famous for their hourglass figures."
		%></p>
	</div>

</div>
<hr>

<%= render partial: "shape_programmes", :locals => { shape_programmes: @hour_glass_programmes } %>

app/views/admin_programs/injuries.html.erb
<div class="signlog">
  <%= render "shared/sign_up_log_in" %>
</div>

<div class="temptitle">
	<h1>Common injuries</h1>
</div>

<div class="contocome">
	<p>Content to be added shortly</p>
</div>

app/views/admin_programs/lean.html.erb
<div class="signlog">
  <%= render "shared/sign_up_log_in" %>
</div>

<div class="temptitle">
	<h1>Lean machine</h1>
</div>

<div class="bodyinfowrap">
	<div class="bodyshapeimage">
		<p>image to come</p>
	</div>
	<div class="bodyshapeinfocnt">
		<p><%=
			"Pellentesque convallis varius turpis ut tincidunt. Curabitur fermentum, ante a viverra adipiscing, dolor eros consequat est, eu ultricies risus lectus sollicitudin risus. Etiam eget rutrum purus. Etiam eu ullamcorper ligula. Fusce mi urna, auctor non enim id, varius elementum odio. Cras ut diam orci. Aenean a nibh rutrum, eleifend ligula non, sagittis augue. Quisque id aliquet nisi, ac pulvinar neque."
		%></p>
	</div>

</div>
<hr>

<%= render partial: "shape_programmes", :locals => { shape_programmes: @lean_programmes } %>

app/views/admin_programs/lose.html.erb
<div class="signlog">
  <%= render "shared/sign_up_log_in" %>
</div>

<div class="temptitle">
	<h1>Lose a few</h1>
</div>

<div class="bodyinfowrap">
	<div class="bodyshapeimage">
		<p>image to come</p>
	</div>
	<div class="bodyshapeinfocnt">
		<p><%=
			"Pellentesque convallis varius turpis ut tincidunt. Curabitur fermentum, ante a viverra adipiscing, dolor eros consequat est, eu ultricies risus lectus sollicitudin risus. Etiam eget rutrum purus. Etiam eu ullamcorper ligula. Fusce mi urna, auctor non enim id, varius elementum odio. Cras ut diam orci. Aenean a nibh rutrum, eleifend ligula non, sagittis augue. Quisque id aliquet nisi, ac pulvinar neque."
		%></p>
	</div>

</div>
<hr>


<%= render partial: "shape_programmes", :locals => { shape_programmes: @lose_weight_programmes } %>

app/views/admin_programs/pear.html.erb
<div class="signlog">
  <%= render "shared/sign_up_log_in" %>
</div>

<div class="temptitle">
	<h1>Pear shape</h1>
</div>

<div class="bodyinfowrap">
	<div class="bodyshapeimage">
		<p>image to come</p>
	</div>
	<div class="bodyshapeinfocnt">
		<p><%=
			"The pear shape - Your hip measurements are greater than your bust measurements and your waist is well defined. You typically carry your weight around your hips, bottom and thighs, and it can be very stubborn to shift! You may find that when you lose weight it will come off of your face and upper body rather than where you want it to come off! Beyonce and Jennifer Lopez are famous Pear shape ladies."
		%></p>
	</div>

</div>
<hr>

<%= render partial: "shape_programmes", :locals => { shape_programmes: @pear_shape_programmes } %>