config/routes.rb
Gymsavvy::Application.routes.draw do

  get "exercises/index"

  root to: 'users#new'

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"

  get "bulking_up" => "admin_programs#bulking", :as => "bulking"
  get "lean_machine" => "admin_programs#lean", :as => "lean"
  get "lose_a_few" => "admin_programs#lose", :as => "lose"

  get "pear_shape" => "admin_programs#pear", :as => "pear"
  get "apple_shape" => "admin_programs#apple", :as => "apple"
  get "hour_glass_shape" => "admin_programs#hour", :as => "hour"
  get "celery_shape" => "admin_programs#celery", :as => "celery"

  get "edit/:id" => "program_sets#clone_program", :as => "clone_program"

  get "common_injuries" => "admin_programs#injuries", :as => "injuries"
  get "avoid_injury" => "admin_programs#avoid", :as => "avoid"

  resources :sessions
  resources :users
  resources :program_sets
  resources :exercises

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gymsays!</title>
  <%= stylesheet_link_tag    'custom', 'exercises', 'program_sets', 'users', 'scaffolds', 'admin_programs', :media => :screen %>
  <%= stylesheet_link_tag('print', :media => :print) %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="wrap">

	<div class="maintopbar">
		<div class="maintitlebar"><%= image_tag "title/maintitle.png" %></div>
		<div class="mainnavbar">
			<ul>
				<li class="navlink"><%= link_to "Home", root_path %></li>
				<% if current_user %>
					<% if current_user.admin? %>
						<li class="navlink"><%= link_to "Exercises", exercises_path %></li>
					<% end %>
					<li class="navlink"><%= link_to "My programmes", program_sets_path %></li>
					<li class="navlink"><%= link_to "Log out", log_out_path %></li>
				<% else %>
						<li class="navlink" id="signup"><%= link_to "Sign up", "#" %></li>
						<li class="navlink"  id="login"><%= link_to "log in", "#" %></li>			
				<% end %>
			</ul>
		</div>
	</div>

	<div id="maincontainer">
		<div class="leftside">
			<div class="links">
				<h2>Men's Programmes</h2>
				<ul>
					<li><%= link_to "Bulking up", bulking_path, class: "sidelinks" %></li>
					<li><%= link_to "Lean machine", lean_path, class: "sidelinks" %></li>
					<li><%= link_to "Lose a few", lose_path, class: "sidelinks" %></li>
				</ul>
			</div>
			<div class="links">
				<h2>Women's Programmes</h2>
				<ul>
					<li><%= link_to "Pear Shape", pear_path, class: "sidelinks" %></li>
					<li><%= link_to "Apple Shape", apple_path, class: "sidelinks" %></li>
					<li><%= link_to "Hour Glass Shape", hour_path, class: "sidelinks" %></li>
					<li><%= link_to "Celery Shape", celery_path, class: "sidelinks" %></li>
				</ul>
			</div>
			<div class="links">
				<h2>Injured?</h2>
				<ul>
					<li><%= link_to "Common injuries", injuries_path, class: "sidelinks" %></li>
					<li><%= link_to "How to avoid injury", avoid_path, class: "sidelinks" %></li>
				</ul>
			</div>
		</div>

		<div id="container">

			<% flash.each do |name, msg| %>
			  <%= content_tag :div, msg, :class => male_female('flash') %>
			<% end %>

			<%= yield %>
		</div>

		<div class="rightside">
			<div class="advertising">
				<h1>Adverts</h1>
				<div class="image">
					<%= image_tag "protein_shake.gif", :alt => "protein shake" %>
				</div>
				<div class="image">
					<%= image_tag "sand_bell.gif", :alt => "sand bell" %>
				</div>
			</div>
		</div>
	</div>

</div>
<div class="clearfooter"></div>
	<div class="foot">
		<div class="personalinfo">
			<p>support@gymsays.co.uk<br /><br />
				Created by Sam Thomas<br />
				www.samthomas-dev.co.uk<br />
				
			</p>
		</div>
	</div>

</body>
</html>